### ISSUE TITLE
Bug à l'instal

### ISSUE THREAD

**Issue by EyaraWS** [jean-pasqualini/import#31]
Cocur slugify à mettre dans les dépencances
Monolog à autoriser à partir de la version 2.12.1

Cannot autowire slugify
Cannot autowire "Symfony\Component\PropertyAccess\PropertyAccessor"
Vérifier l'existance de l'extension pcntl
Attention avec les logger qui sont en private

**Comment by jean-pasqualini** [comment]
@EyaraWS Bonjour, nous avons corrigé la plupart des bugs dans une nouvelle release de la 0.3 (0.3.1) et dans la branche de dev de la 0.4.

Concernant l'extension pcntl, ce problème ne touchant que la 0.4 en cours de développement, nous allons fixer ce problème dans une PR dédié.

Merci.

**Comment by jean-pasqualini** [comment]
@EyaraWS Concernant l'extension pcntl, une pr est en cours pour ne pas l'utiliser si elle n'est pas disponible sur votre système php.

Cependant, même si elle n'est pas obligatoire. il est recommandé de l'installé pour permettre en cas d'arrrêt du processus de ne pas s'arrêter en pleine transaction doctrine par exemple.

Voir https://github.com/jean-pasqualini/import/pull/34.

Je close donc ce ticket.
